package com.ds.factory.datasource.mappers;

import com.ds.factory.datasource.entities.UserBusiness;
import com.ds.factory.dao.Example.UserBusinessExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_userbusiness
     *
     * @mbggenerated
     */
    int countByExample(UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_userbusiness
     *
     * @mbggenerated
     */
    int deleteByExample(UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_userbusiness
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_userbusiness
     *
     * @mbggenerated
     */
    int insert(UserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_userbusiness
     *
     * @mbggenerated
     */
    int insertSelective(UserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_userbusiness
     *
     * @mbggenerated
     */
    List<UserBusiness> selectByExample(UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_userbusiness
     *
     * @mbggenerated
     */
    UserBusiness selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_userbusiness
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserBusiness record, @Param("example") UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_userbusiness
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserBusiness record, @Param("example") UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_userbusiness
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_userbusiness
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserBusiness record);
}