package com.ds.factory.datasource.entities;

import java.util.Date;
import lombok.Data;

@Data
public class Order_Form {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 05 08:24:52 CST 2020
     */
    private String Order_no;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 05 08:24:52 CST 2020
     */
    private String Client_no;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 05 08:24:52 CST 2020
     */
    private String Staff_no;//销售部负责人

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 05 08:24:52 CST 2020
     */
    private Date Order_Create_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 05 08:24:52 CST 2020
     */
    private Long Order_sum_amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 05 08:24:52 CST 2020
     */
    private String Progress;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 05 08:24:52 CST 2020
     */
    private Long Liquidated_damages;//违约金

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 05 08:24:52 CST 2020
     */
    private Long Check;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 05 08:24:52 CST 2020
     */
    private Date Update_date;


    public String getOrder_no() {return Order_no;}
    public void setOrder_no(String order_no) {this.Order_no = order_no == null ? null : order_no.trim();}

    public String getClient_no() {return Client_no;}
    public void setClient_no(String client_no) {this.Client_no = client_no == null ? null : client_no.trim();}

    public String getStaff_no() {return Staff_no;}
    public void setStaff_no(String staff_no) {this.Staff_no = staff_no == null ? null : staff_no.trim();}

    public Date getOrder_Create_date() {return Order_Create_date;}
    public void setOrder_Create_date(Date order_Create_date) { this.Order_Create_date = order_Create_date == null ? null : order_Create_date; }

    public Long getOrder_sum_amount() {return Order_sum_amount;}
    public void setOrder_sum_amount(Long order_sum_amount) {Order_sum_amount = order_sum_amount;}

    public String getProgress() {return Progress;}
    public void setProgress(String progress) {this.Progress = progress == null ? null : progress.trim();}

    public Long getLiquidated_damages() {return Liquidated_damages;}
    public void setLiquidated_damages(Long liquidated_damages) {Liquidated_damages = liquidated_damages;}

    public Long getCheck() {return Check;}
    public void setCheck(Long check) {Check = check;}

    public Order_Form() {

    }

    public Order_Form(String Order_no,	        String Client_no,	        String Staff_no,
                      Date Order_Create_date,	Long Order_sum_amount,
                      String Progress,	        Long Liquidated_damages,    Long Check,
                      Date Update_date) {
        this.Order_no=Order_no;
        this.Client_no=Client_no;
        this.Staff_no=Staff_no;
        this.Order_Create_date=Order_Create_date;
        this.Order_sum_amount=Order_sum_amount;
        this.Progress=Progress;
        this.Liquidated_damages=Liquidated_damages;
        this.Check=Check;
        this.Update_date=Update_date;
    }

    public Date getUpdate_date() {
        return Update_date;
    }

    public void setUpdate_date(Date update_date) {
        Update_date = update_date;
    }
}
